version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citefull
      - MONGO_INITDB_ROOT_PASSWORD=Citefull2021!
    ports:
      - 27017:27017
    volumes:
      # maps our mongo-init.js to a path inside the container image. docker-entrypoint.sh will execute this file
      # during container initialization.
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # maps the directory ot which we mounted the EBS volume to /data/db, the default data directory
      # used by mongo
      - /mongo-data:/data/db
